### ISSUE TITLE
Unable to install using github_install

### ISSUE THREAD

**Issue by thuwas** [Azure/AzureQstor#1]
![image](https://user-images.githubusercontent.com/41892235/83208259-81065c00-a198-11ea-87ef-a7a123289c26.png)

Getting error: Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot download all files

Is this supported by R version 3.3 ?

**Comment by hongooi73** [comment]
AzureQstor should work on R 3.3. But that error has nothing to do with AzureQstor; you're having a problem downloading the package from Github. You might need to update devtools, or check that your network connection is working.
